import cn from "classnames";
import Brand from "components/Brand";
import Button from "components/Button";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import TrendsIcon from "components/Icons/TrendsIcon";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import Slider from "components/Slider";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useIsomorphicLayoutEffect } from "hooks/useIsomorphicLayoutEffect";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useEffect, useState } from "react";
import Sticky, { Status } from "react-stickynode";
import styles from "styles/SupplyChain.module.scss";
import TabSection, { TabData } from "views/fim/TabSection";

gsap.registerPlugin(ScrollTrigger);
const tabDataList: TabData[] = [
  {
    title: "Trends",
    des: [
      "以全网电商大数据为基础，帮助企划人员分析流行趋势与快速创款的AI智能平台",
    ],
    image: "/images/fim/fim-trends.png",
  },
  {
    title: "Studio",
    des: ["高逼真虚拟样品减少实物开发", "加快产品设计效率", "缩短产品上市周期"],
    image: "/images/fim/fim-studio.png",
  },
  {
    title: "Manager",
    des: [
      "一站式产品在线协同管理平台，通过整合产品企划、款式设计、开发全链路信息，实现跨部门云端协同、共享项目进度，为企业中的不同角色提供实时进度管理与决策方案，标准化产品研发流程。",
    ],
    image: "/images/fim/fim-manager.png",
  },
  {
    title: "Library",
    des: [
      "专为时尚企业提供的数字化资产管理工具，通过标准化数据帮助客户实现数字化资产的高效调用和规范管理，提高设计和开发效率。",
    ],
    image: "/images/fim/fim-library.png",
  },
];
const stickyDataList: TabData[] = [
  {
    title: "Trends",
    des: [
      "以全网电商大数据为基础，帮助企划人员分析流行趋势与快速创款的AI智能平台",
    ],
    image: "/images/fim/fim-trends.png",
  },
  {
    title: "Studio",
    des: ["高逼真虚拟样品减少实物开发", "加快产品设计效率", "缩短产品上市周期"],
    image: "/images/fim/fim-studio.png",
  },
  {
    title: "Manager",
    des: [
      "一站式产品在线协同管理平台，通过整合产品企划、款式设计、开发全链路信息，实现跨部门云端协同、共享项目进度，为企业中的不同角色提供实时进度管理与决策方案，标准化产品研发流程。",
    ],
    image: "/images/fim/fim-manager.png",
  },
  {
    title: "Library",
    des: [
      "专为时尚企业提供的数字化资产管理工具，通过标准化数据帮助客户实现数字化资产的高效调用和规范管理，提高设计和开发效率。",
    ],
    image: "/images/fim/fim-library.png",
  },
];
//use sticky
const SupplyChain: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  const handleStickyStateChange = (status: Status) => {
    console.log(status);
  };
  return (
    <Layout>
      <Head>
        <title>SupplyChain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          image="/images/manager.jpg"
          title="供应链"
          subtitle="鞋服箱包 数字化智能供应链"
          description="从智能选款到大货交付，为鞋,服,箱包等行业提供一体化端到端的开发生产服务"
          buttonText="免费使用"
        />
        <div className="bg-rev-bg-black-0B py-26 relative">
          <div className={styles["blur"]}></div>
          <div className="container">
            <h2 className="section-title">业务亮点</h2>
            <Tabbar
              activeIndex={tabActiveIndex}
              items={[
                { icon: "trends", text: "急速设计" },
                { icon: "studio", text: "专业团队" },
                { icon: "manager", text: "便捷改款" },
                { icon: "library", text: "柔性匹配" },
              ]}
              onItemChange={(index) => {
                setTabActiveIndex(index);
              }}
            />
            <TabSection data={tabDataList[tabActiveIndex]} />
          </div>
        </div>
        {/**从企划到生产 仅需21天的极速业务流程 */}
        <div className="bg-rev-bg-black-12">
          <div className="container">
            <h2 className="section-title pt-47/2">
              从企划到生产 仅需21天的极速业务流程
            </h2>
            <Sticky
              enabled={true}
              top={0}
              bottomBoundary={"#tab3"}
              onStateChange={handleStickyStateChange}
            >
              <div className="bg-rev-bg-black-12">
                <div style={{ height: 70 }}></div>
                <div className="w-4/5 mx-auto">
                  <Step
                    className="flex-1"
                    selectedIndex={0}
                    list={[
                      { index: 1, text: "企划" },
                      { index: 2, text: "设计鞋底" },
                      { index: 3, text: "楦体确认 设计手稿" },
                      { index: 4, text: "验证出货" },
                    ]}
                  ></Step>
                </div>
              </div>
            </Sticky>
            {stickyDataList.map((item, index) => {
              return (
                <div
                  id={`tab${index}`}
                  key={String(index)}
                  className="container w-4/5"
                >
                  <TabSection center simple data={item} />
                </div>
              );
            })}
          </div>
        </div>
        {/** 和REVOBIT生态链接  */}
        <div className="bg-rev-bg-black-12">
          <div className="container">
            <h2 className="section-title py-47/2" style={{ margin: 0 }}>
              和REVOBIT生态链接
            </h2>
            <SectionCard
              title="智能企划 极速选款"
              mode={"left"}
              className="pb-37"
              list={[
                {
                  icon: "/images/trends/i17.png",
                  text: "一段文字介绍内容",
                },
                {
                  icon: "/images/trends/i8.png",
                  text: "一段文字介绍内容",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/智能化搜索.png"
                  fill
                  className="image"
                  alt="智能化搜索"
                />
              </div>
            </SectionCard>
            <SectionCard
              title="线上选材 高效整合"
              mode={"right"}
              className="pb-37"
              list={[
                {
                  icon: "/images/trends/i17.png",
                  text: "无缝兼容Adob​​e Illustrator®及Photoshop设计软件",
                },
                {
                  icon: "/images/trends/i8.png",
                  text: "能够打通CLO设计软件，实现线上协同管理",
                },
                {
                  icon: "/images/trends/i8.png",
                  text: "与Revofim Studio无缝协作，流畅开展从3D设计样图到实际落地全过程",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/智能化搜索.png"
                  fill
                  className="image"
                  alt="智能化搜索"
                />
              </div>
            </SectionCard>
            <SectionCard
              title="简单开版 便捷管理"
              mode={"left"}
              className="pb-37"
              list={[
                {
                  icon: "/images/trends/i17.png",
                  text: "按照企业的产品线、开发模式等维度自定义专属开发流程",
                },
                {
                  icon: "/images/trends/i8.png",
                  text: "通过流程驱动业务单据",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/智能化搜索.png"
                  fill
                  className="image"
                  alt="智能化搜索"
                />
              </div>
            </SectionCard>
          </div>
        </div>
        {/* 全球合作伙伴 */}
        <div className="bg-rev-bg-black-0B pb-32">
          <div className="container mb-12">
            <h2 className="section-title pt-26">谁选择了FIM？</h2>
          </div>
          <Brand />
        </div>
        <div className="bg-rev-bg-contact">
          <div className="container pb-32">
            <h2 className="section-title pt-26">联系我们</h2>
            <h3 className="section-subtitle">即刻体验数字时尚创新之旅</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "zh", ["common"])),
  },
});

export default SupplyChain;
