import cn from "classnames";
import Brand from "components/Brand";
import Button from "components/Button";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import TrendsIcon from "components/Icons/TrendsIcon";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import Slider from "components/Slider";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import { useIsomorphicLayoutEffect } from "hooks/useIsomorphicLayoutEffect";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useEffect, useState } from "react";
import Sticky from "react-stickynode";
import styles from "styles/Fim.module.scss";
import TabSection, { TabData } from "views/fim/TabSection";

import Category from "../../views/fim/Category";

const tabDataList: TabData[] = [
  {
    title: "Trends",
    des: ["基于海量数据分析，借助AI智能精准洞察趋势打造爆款"],
    image: "/images/fim/fim-trends.png",
  },
  {
    title: "Studio",
    des: ["交互式3D实时查看与设计，帮助信息无缝沟通传达"],
    image: "/images/fim/fim-studio.png",
  },
  {
    title: "Manager",
    des: ["实时掌控工作进度，推动关键流程运转，提升整体效率"],
    image: "/images/fim/fim-manager.png",
  },
  {
    title: "Library",
    des: ["集中管理、沉淀数字资产，实现数字资产的共享与敏捷调用"],
    image: "/images/fim/fim-library.png",
  },
];
const links: string[] = [
  "/trends.html",
  "",
  "/fim/manager.html",
  "/fim/library.html",
];
//use sticky
const Fim: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  return (
    <Layout>
      <Head>
        <title>Revofim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          image="/images/fim.png"
          title={
            <div className="relative w-80 mx-auto">
              <Image
                src={"/images/icon/fim.png"}
                fill
                className="image"
                alt=""
              />
            </div>
          }
          subtitle="时尚行业首个端到端全链路数字化解决方案"
          description="FIM（Fashion Information Modelling），即“时尚信息模型”—通过构建企划、设计、研发、生产、销售全生命周期流程，实现端到端全链路的信息协同与数字化管理,助力时尚产业实现可持续发展。"
          buttonText={["登录Revofim Web端", "下载Revofim PC端"]}
          buttonClassnames={[
            cn(styles["banner-primary-btn"], styles["banner-btn"]),
            styles["banner-btn"],
          ]}
        />
        <Category />

        <div className="bg-rev-bg-contact py-26">
          <div className="container">
            <h2 className="section-title">FIM全链路数字化解决方案</h2>
            <Tabbar
              activeIndex={tabActiveIndex}
              items={[
                { icon: "trends", text: "Trends" },
                { icon: "studio", text: "Studio" },
                { icon: "manager", text: "Manager" },
                { icon: "library", text: "Library" },
              ]}
              onItemChange={(index) => {
                setTabActiveIndex(index);
              }}
            />
            <TabSection
              key={String(tabActiveIndex)}
              data={tabDataList[tabActiveIndex]}
              onButtonClick={() => {
                location.href = links[tabActiveIndex];
              }}
            />
          </div>
        </div>
        {/* 全球合作伙伴 */}
        <div className="bg-rev-bg-black-0B pb-32">
          <div className="container mb-12">
            <h2 className="section-title pt-26">谁选择了FIM？</h2>
          </div>
          <Brand />
        </div>
        <div className="bg-rev-bg-contact">
          <div className="container pb-32">
            <h2 className="section-title pt-26">联系我们</h2>
            <h3 className="section-subtitle">即刻体验数字时尚创新之旅</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Fim;
