import e2e from "assets/images/e2e.png";
import cn from "classnames";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import Slider from "components/Slider";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import { useIsomorphicLayoutEffect } from "hooks/useIsomorphicLayoutEffect";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useEffect, useState } from "react";
import styles from "styles/Fim.module.scss";
import TabSection, { TabData } from "views/fim/TabSection";
import Tips from "views/fim/Tips";
const tabDataList: TabData[] = [];
//use sticky
const Library: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  return (
    <Layout>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          id="manager-banner"
          image="/images/manager.jpg"
          title={
            <div className="relative w-150">
              <Image
                src="/images/library/library-title.png"
                className="image"
                fill
                alt=""
              />
            </div>
          }
          description="数字资产存储中枢，多场景赋能产品创意设计，让管资产、玩设计、做产品的方法变得更简单、高效。"
          buttonText="免费使用"
        />

        <div className="bg-rev-bg-contact relative">
          <div className={styles["lib-bg"]}></div>
          <Tips />
          <div className="container">
            <div className="my-10">
              <h2 className="section-title" style={{ marginTop: 0 }}>
                核心业务场景
              </h2>
            </div>
            <div className="h-16"></div>
            <SectionCard
              title={"标签化数据"}
              subtitle="通过“标签化”打造企业内部价值共识"
              mode={"left"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/标签化数据-1.png",
                  text: "文本数据：自定义字段，按需搭建不同类型的库",
                },
                {
                  icon: "/images/library/标签化数据-2.png",
                  text: "可视化数据：标准化设备及流程展示素材效果",
                },
                {
                  icon: "/images/library/标签化数据-3.png",
                  text: "设计元数据：打通各种设计软件",
                },
                {
                  icon: "/images/library/标签化数据-4.png",
                  text: "标签体系：与权威机构共建产业标签标准，助力打造品牌私有资产标签体系",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/标签化数据.png"
                  fill
                  className="image"
                  alt="标签化数据"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"智能化搜索"}
              subtitle="快速的智能搜索能力，秒级调取素材"
              mode={"right"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/智能化搜索-1.png",
                  text: "精准筛选搜索",
                },
                {
                  icon: "/images/library/智能化搜索-2.png",
                  text: "多维度关键词筛选内容",
                },
                {
                  icon: "/images/library/智能化搜索-3.png",
                  text: "AI智能搜索",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/智能化搜索.png"
                  fill
                  className="image"
                  alt="智能化搜索"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"可视化管理"}
              subtitle="数字资产使用情况一目了然"
              mode={"left"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/可视化管理-1.png",
                  text: "灵活的自定义分析功能",
                },
                {
                  icon: "/images/library/可视化管理-2.png",
                  text: "多场景的分析图表",
                },
                {
                  icon: "/images/library/可视化管理-3.png",
                  text: "定制化数据统计",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/可视化管理.png"
                  fill
                  className="image"
                  alt="可视化管理"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"整合数字资产"}
              subtitle="打通外部软件及工具，整合并沉淀数字资产"
              mode={"right"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/整合数字资产-1.png",
                  text: "杜绝内容数据孤岛：与企业其他系统平台进行安全集成，整合并沉淀零散的内容资源",
                },
                {
                  icon: "/images/library/整合数字资产-2.png",
                  text: "协助打造企业级设计研发流程：搭配revobit其他产品模块或与外部系统工具打通，实现数字内容资产的全方位管理",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/整合数字资产.png"
                  fill
                  className="image"
                  alt="整合数字资产"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"灵活设置安全权限"}
              subtitle="按需设置权限，保障数据安全"
              mode={"left"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/灵活设置安全权限-1.png",
                  text: "跟踪素材调用操作日志，避免误操作和违规使用",
                },
                {
                  icon: "/images/library/灵活设置安全权限-2.png",
                  text: "严密的访问分级、根据实际需要创建部门架构和内容浏览权限",
                },
                {
                  icon: "/images/library/灵活设置安全权限-3.png",
                  text: "数据快速备份和恢复、内嵌数字水印等安全机制",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/灵活设置安全权限.png"
                  fill
                  className="image"
                  alt="灵活设置安全权限"
                />
              </div>
            </SectionCard>
          </div>
        </div>
        <div className="bg-rev-bg-black-0B">
          <div className="container pb-32">
            <h2 className="section-title pt-47/2">联系我们</h2>
            <h3 className="section-subtitle">开启资产数字化之路</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Library;
