import Layout from "components/Layout";
import { NextPage } from "next";
import Head from "next/head";
import styles from "styles/About.module.scss";
const About: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>时谛智能</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.about}></div>
    </Layout>
  );
};
export default About;
