import cn from "classnames";
import BigCard from "components/BigCard";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import SmallCard from "components/SmallCard";
import Tabbar from "components/Tabbar";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useState } from "react";
import styles from "styles/Verse.module.scss";
import BrandService from "views/verse/BrandService";
import FunctionSection from "views/verse/FunctionSection";
import QRcodeSection from "views/verse/QRcodeSection";

const Versebook: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  return (
    <Layout>
      <Head>
        <title>Versebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          id="versebook-banner"
          className={styles["banner"]}
          image="/images/versebook.png"
          title={
            <div className="relative w-150">
              <Image
                src="/images/verse/versebook.png"
                className="image"
                fill
                alt=""
              />
            </div>
          }
          description="时尚产业高质量数字化面料平台：脱离冗杂的实物材料和平面信息，让Versebook带你沉浸式体验数字化面料的生命力。"
          buttonText="免费使用"
        />
        <div className="bg-black relative py-47/2">
          <div className="blur-bg"></div>
          <div className="container">
            <h2 className="section-title">产品功能</h2>
            {/*
            <Tabbar
              simple
              activeIndex={tabActiveIndex}
              items={[{ text: "买家" }, { text: "卖家" }]}
              onItemChange={(index) => {
                setTabActiveIndex(index);
              }}
            />*/}
            <FunctionSection
              items={[
                {
                  icon: "/images/verse/数字化材料库.png",
                  title: "数字化材料库",
                  description: "专注鞋服行业数字化材料图书馆",
                },
                {
                  icon: "/images/verse/3D可视化.png",
                  title: "3D可视化",
                  description: "虚拟仿真实物效果",
                },
                {
                  icon: "/images/verse/标准色彩库.png",
                  title: "标准色彩库",
                  description: "潘通、Color、建立个人搭配色板",
                },
                {
                  icon: "/images/verse/精准搜索.png",
                  title: "精准搜索",
                  description: "标准化信息便于快速找到材料",
                },
                {
                  icon: "/images/verse/助力设计.png",
                  title: "助力设计",
                  description: "打通2D、3D设计软件",
                },
                {
                  icon: "/images/verse/分享.png",
                  title: "分享",
                  description: "与他人共享材料",
                },
                {
                  icon: "/images/verse/收藏.png",
                  title: "收藏",
                  description: "建立个人灵感素材库,收集灵感素材",
                },
                {
                  icon: "/images/verse/样品申请.png",
                  title: "样品申请",
                  description: "申请实物样品",
                },
              ]}
            />
          </div>
        </div>

        <div className="bg-rev-bg-black-10 relative pb-36">
          <div className="container">
            <h2 className="section-title py-47/2">品牌</h2>
            <SectionCard
              grid
              card
              gapClassName={"w-10"}
              title={"提供真实有效的数字化材料及供应商资源"}
              subtitle="汇集并持续更新时尚产业材料资源，精准的搜索渠道大幅提升找料效率，真正脱离冗杂的实物材料和平面信息，让versebook带你沉浸式体验数字化面料的生命力。"
              mode={"left"}
              list={[
                {
                  icon: "/images/verse/品牌-1.png",
                  text: "搜索材料",
                },
                {
                  icon: "/images/verse/品牌-2.png",
                  text: "寻求合作",
                },
                {
                  icon: "/images/verse/品牌-3.png",
                  text: "赋能设计",
                },
                {
                  icon: "/images/verse/品牌-4.png",
                  text: "搭配色板",
                },
                {
                  icon: "/images/verse/品牌-5.png",
                  text: "灵感素材库",
                },
                {
                  icon: "/images/verse/品牌-6.png",
                  text: "分享材料",
                },
                {
                  icon: "/images/verse/品牌-7.png",
                  text: "3D可视化",
                },
                {
                  icon: "/images/verse/品牌-8.png",
                  text: "样品申请",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <div
                  style={{
                    background: "#1A1A35",
                    borderRadius: " 30px",
                    padding: "60px",
                  }}
                >
                  <Image
                    src="/images/verse/品牌.png"
                    fill
                    className="image"
                    alt="品牌"
                  />
                </div>
              </div>
            </SectionCard>
          </div>
        </div>

        <div className="bg-black relative pb-36">
          <div className="container">
            <h2 className="section-title py-47/2">供应商</h2>
            <SectionCard
              grid
              gapClassName={"w-10"}
              title={"时尚行业高质量数字化面料平台"}
              subtitle="Versebook开创了以高精建模+实时渲染展示面料效果的先河，让材料不再止于无力的照片样品，而真正将现实照进虚拟，助力供应商、渠道商随时随地掌握先机。"
              mode={"right"}
              list={[
                {
                  icon: "/images/verse/供应商-1.png",
                  text: "标准化材料库",
                },
                {
                  icon: "/images/verse/供应商-2.png",
                  text: "材料管理",
                },
                {
                  icon: "/images/verse/供应商-3.png",
                  text: "营销工具",
                },
                {
                  icon: "/images/verse/供应商-4.png",
                  text: "从实物到数字化",
                },
                {
                  icon: "/images/verse/供应商-5.png",
                  text: "维护及拓客",
                },
                {
                  icon: "/images/verse/供应商-6.png",
                  text: "搭建颜色库",
                },
                {
                  icon: "/images/verse/供应商-7.png",
                  text: "数据统计及分析",
                },
                {
                  icon: "/images/verse/供应商-8.png",
                  text: "3D材料展示API",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <div
                  style={{
                    background: "#0F0F1F",
                    borderRadius: " 30px",
                    padding: "60px",
                  }}
                >
                  <Image
                    src="/images/verse/供应商.png"
                    fill
                    className="image"
                    alt="供应商"
                  />
                </div>
              </div>
            </SectionCard>
          </div>
        </div>

        {/**为您提供如下品牌服务 */}
        <div className="bg-black relative pt-20 pb-30">
          <BrandService />
        </div>
        <div className="bg-rev-bg-black-10 relative pb-36">
          <div className="container">
            <h2 className="section-title py-47/2">设计师</h2>
            <SectionCard
              title={"专注鞋服行业的数字化材料图书馆"}
              subtitle="运用行业领先数字化材料方案，提升时尚创意水平，打破灵感边界，让设计随心所欲。"
              mode={"left"}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/verse/d1.png"
                  fill
                  className="image"
                  alt="专注鞋服行业的数字化材料图书馆"
                />
              </div>
            </SectionCard>
            <SectionCard
              className="py-30"
              title={"数字化设计 赋能2D设计"}
              subtitle="数字化材料与2D设计工具结合，例如Adobe Illustrator、Photoshop。只需一键填充即可将数字化材料运用于设计稿上，灵感即刻落地设计。"
              mode={"right"}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/verse/d2.png"
                  fill
                  className="image"
                  alt="数字化设计"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"设计畅想 协作无界"}
              subtitle="满足设计师在3D模型上实时进行材料及色彩搭配的设计需求，达到逼真还原设计的效果。"
              mode={"left"}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/verse/d3.png"
                  fill
                  className="image"
                  alt="设计畅想"
                />
              </div>
            </SectionCard>
          </div>
        </div>
        <div className="bg-black">
          <div className="container pb-36">
            <h2 className="section-title pt-47/2 pb-18">开始你的数字化之旅</h2>
            <QRcodeSection />
          </div>
        </div>
        <div className="bg-rev-bg-black-10">
          <div className="container pb-36">
            <h2 className="section-title pt-47/2">咨询Versebook</h2>
            <h3 className="section-subtitle">为数字化设计赋能</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Versebook;
