import { Environment, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { useLoader } from "@react-three/fiber";
import { useControls } from "leva";
import Head from "next/head";
import { Suspense, useEffect, useState, useTransition } from "react";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

const Test = () => {
  useEffect(() => {
    const modelViewerTransform = document.querySelector(
      "model-viewer#transform"
    );
  }, []);
  return (
    <>
      <Head>
        <title>Revcbit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="module"
          async
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
        ></script>
      </Head>
      <div className="absolute left-0 top-0 bottom-0 right-0">
        <model-viewer
          id="transform"
          scale="12 12 12"
          orientation="20deg 0 0"
          style={{ width: 600 }}
          alt="Neil Armstrong's Spacesuit from the Smithsonian Digitization Programs Office and National Air and Space Museum"
          src="https://test-20221101.revobit.cn/static/shoe.gltf"
          ar
          shadow-intensity="1"
          camera-controls
        ></model-viewer>
      </div>
    </>
  );
};
export default Test;
