import Layout from "components/Layout";
import { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Cad.module.scss";
import Banner from "views/cad/Banner";
import Design from "views/cad/Design";
import Eco from "views/cad/Eco";
import Highlights from "views/cad/Highlights";
import Library from "views/cad/Library";
import Process from "views/cad/Process";
const Cad: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>时谛智能</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.cad}>
        <Banner />
        <Highlights />
        <Design />
        <Process />
        <Eco />
        <Library />
      </div>
    </Layout>
  );
};

export default Cad;
