import e2e from "assets/images/e2e.png";
import Brand from "components/Brand";
import Button from "components/Button";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import TrendsIcon from "components/Icons/TrendsIcon";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import Slider from "components/Slider";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useIsomorphicLayoutEffect } from "hooks/useIsomorphicLayoutEffect";
import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import Sticky from "react-stickynode";
import styles from "styles/Fim.module.scss";

import Category from "./components/Category";
import TabSection, { TabData } from "./components/TabSection";
gsap.registerPlugin(ScrollTrigger);
const tabDataList: TabData[] = [
  {
    title: "Trends",
    des: [
      "以全网电商大数据为基础，帮助企划人员分析流行趋势与快速创款的AI智能平台",
    ],
    image: "/images/fim/fim-trends.png",
  },
  {
    title: "Studio",
    des: ["高逼真虚拟样品减少实物开发", "加快产品设计效率", "缩短产品上市周期"],
    image: "/images/fim/fim-studio.png",
  },
  {
    title: "Manager",
    des: [
      "一站式产品在线协同管理平台，通过整合产品企划、款式设计、开发全链路信息，实现跨部门云端协同、共享项目进度，为企业中的不同角色提供实时进度管理与决策方案，标准化产品研发流程。",
    ],
    image: "/images/fim/fim-manager.png",
  },
  {
    title: "Library",
    des: [
      "专为时尚企业提供的数字化资产管理工具，通过标准化数据帮助客户实现数字化资产的高效调用和规范管理，提高设计和开发效率。",
    ],
    image: "/images/fim/fim-library.png",
  },
];
//use sticky
const Fim: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  return (
    <Layout>
      <Head>
        <title>Revcfim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          image="/images/manager.jpg"
          title={
            <div className="relative w-80 mx-auto">
              <Image
                src={"/images/icon/fim.png"}
                fill
                className="image"
                alt=""
              />
            </div>
          }
          subtitle="时尚行业首个端到端全链路数字化解决方案"
          description="FIM（Fashion Information Modelling），即“时尚信息模型”—通过构建企划、设计、制样、生产、销售全生命周期流程，实现端到端全链路的信息协同与数字化管理,助力时尚产业实现可持续发展。"
          buttonText={["登录Revofim Web端", "下载Revofim PC端"]}
          buttonClassnames={[styles["banner-primary-btn"]]}
        />
        <Category />

        <div className="bg-rev-bg-contact py-6">
          <div className="container">
            <h2 className="section-title">FIM全链路数字化解决方案</h2>
            <Tabbar
              activeIndex={tabActiveIndex}
              items={[
                { icon: "trends", text: "Trends" },
                { icon: "studio", text: "Studio" },
                { icon: "manager", text: "Manager" },
                { icon: "library", text: "Library" },
              ]}
              onItemChange={(index) => {
                setTabActiveIndex(index);
              }}
            />
            <TabSection data={tabDataList[tabActiveIndex]} />
          </div>
        </div>
        {/* 全球合作伙伴 */}
        <div className="bg-rev-bg-black-0B pb-32">
          <div className="container mb-12">
            <h2 className="section-title mt-0">谁选择了FIM？</h2>
          </div>
          <Brand />
        </div>
        <div className="bg-rev-bg-contact">
          <div className="container pb-32">
            <h2 className="section-title">联系我们</h2>
            <h3 className="section-subtitle">即刻体验数字时尚创新之旅</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default Fim;
