import type { NextPage } from "next";
import Head from "next/head";
import PocketBase from "pocketbase";
import { useEffect } from "react";
import styles from "styles/Home.module.scss";

import Layout from "../components/Layout";
const client = new PocketBase("https://pocketbase.io");

const Home: NextPage = () => {
  useEffect(() => {
    //client.records.getList("posts", 1, 20, {});
  }, []);
  return (
    <Layout>
      <Head>
        <title>Create Next App Heelo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles["top-banner"]}>
          <video
            className={styles["bg-video"]}
            autoPlay={true}
            loop={true}
            muted={true}
            controls={false}
          >
            <source src="https://vjs.zencdn.net/v/oceans.mp4"></source>
          </video>
          <div className={styles["mask"]}>
            <div className="container">0000</div>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
