import e2e from "assets/images/e2e.png";
import Button from "components/Button";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import Slider from "components/Slider";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useIsomorphicLayoutEffect } from "hooks/useIsomorphicLayoutEffect";
import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import StickyBox from "react-sticky-box";
import Sticky from "react-stickynode";
import styles from "styles/Fim.module.scss";

import Category from "./sections/fim/Category";
import TabSection, { TabData } from "./sections/fim/TabSection";
gsap.registerPlugin(ScrollTrigger);
const tabDataList: TabData[] = [
  {
    title: "Trends",
    des: [
      "以全网电商大数据为基础，帮助企划人员分析流行趋势与快速创款的AI智能平台",
    ],
  },
  {
    title: "Studio",
    des: ["高逼真虚拟样品减少实物开发", "加快产品设计效率", "缩短产品上市周期"],
  },
  {
    title: "Manager",
    des: [
      "一站式产品在线协同管理平台，通过整合产品企划、款式设计、开发全链路信息，实现跨部门云端协同、共享项目进度，为企业中的不同角色提供实时进度管理与决策方案，标准化产品研发流程。",
    ],
  },
  {
    title: "Library",
    des: [
      "专为时尚企业提供的数字化资产管理工具，通过标准化数据帮助客户实现数字化资产的高效调用和规范管理，提高设计和开发效率。",
    ],
  },
];
//use sticky
const Manager: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  return (
    <Layout>
      <Head>
        <title>Create Next App Heelo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          image="/images/manager.jpg"
          title="MANAGER"
          subtitle="产品管理，从品牌企业的商品规划为起始，管理贯穿商品，款式设计，开发，选定货会，大货技转的全链路解决方案。"
          buttonText="免费使用"
        />
        <div className="bg-rev-bg-black py-6">
          <div className="container">
            <h2 className="section-title">业务主流程</h2>
            <Step
              selectedIndex={8}
              list={[
                { index: 1, text: "数字企划" },
                { index: 2, text: "设计规划及任务分配" },
                { index: 3, text: "材料颜色规划" },
                { index: 4, text: "产品设计开发" },
                { index: [5, 6], text: ["3D流程", "2D流程"] },
                { index: 7, text: "样品开发" },
                { index: 8, text: "评审管理" },
                { index: 9, text: "BOM/Pre-cost" },
                { index: 10, text: "生产技转" },
              ]}
            ></Step>
            <div className="container w-4/5">
              <TabSection simple data={tabDataList[tabActiveIndex]} />
            </div>
          </div>
        </div>
        <div className="bg-rev-bg-contact py-6">
          <div className="container">
            <h2 className="section-title">为什么选择Manager</h2>
            <SectionCard
              title={"设计高效协同"}
              mode={"left"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "1",
                },
                { icon: "", text: "2" },
              ]}
            >
              111
            </SectionCard>
            <SectionCard
              title={"开放兼容"}
              mode={"right"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "1",
                },
                { icon: "", text: "2" },
              ]}
            >
              111
            </SectionCard>
            <SectionCard
              title={"设计高效协同"}
              mode={"left"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "1",
                },
                { icon: "", text: "2" },
              ]}
            >
              111
            </SectionCard>
            <SectionCard
              title={"信息互通共享"}
              mode={"right"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "IM实时通话功能，随时随地进行讨论和决策",
                },
                {
                  icon: "",
                  text: "2D设计及3D设计二维码动态分享，让商品端和供应链端同步产品开发状态，避免不必要的开发。",
                },
                {
                  icon: "",
                  text: "通过评审管理功能快速反馈并解决款式、设计环境等问题。",
                },
              ]}
            >
              111
            </SectionCard>
            <SectionCard
              title={"进度实时管理"}
              mode={"left"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "按照企业的产品线、开发模式等维度自定义专属开发流程",
                },
                { icon: "", text: "通过流程驱动业务单据" },
              ]}
            >
              111
            </SectionCard>
            <SectionCard
              title={"开放兼容"}
              mode={"right"}
              className="w-4/5 ml-10"
              list={[
                {
                  icon: "",
                  text: "无缝兼容Adob​​e Illustrator®及Photoshop设计软件",
                },
                { icon: "", text: "能够打通CLO设计软件，实现线上协同管理" },
                {
                  icon: "",
                  text: "与Revofim Studio无缝协作，流畅开展从3D设计样图到实际落地全过程",
                },
              ]}
            >
              111
            </SectionCard>
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default Manager;
