import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "styles/Studio.module.scss";
import Banner from "views/cad/Banner";
import Design from "views/cad/Design";
import Eco from "views/cad/Eco";
import Highlights from "views/cad/Highlights";
import Library from "views/cad/Library";
import Process from "views/cad/Process";
import Card from "views/studio/Card";
import Download from "views/studio/Download";
import Number from "views/studio/Number";
import Slider, { SlideItem } from "views/studio/Slider";
import TabView from "views/studio/TabView";
import TextBanner from "views/studio/TextBanner";
import TopBanner from "views/studio/TopBanner";
const Relation = dynamic(() => import("views/studio/Relation"), { ssr: false });
const s1: SlideItem[] = [
  {
    title: "多端应用",
    image: "/images/studio/多端应用.png",
  },
  {
    title: "公开与私密分享",
    image: "/images/studio/公开与私密分享.png",
  },
  {
    title: "3D批注",
    image: "/images/studio/3D批注.png",
  },
  {
    title: "版本记录",
    image: "/images/studio/版本记录.png",
  },
  {
    title: "在线IM",
    image: "/images/studio/在线IM.png",
  },
  {
    title: "cmf/BOM",
    image: "/images/studio/cmf.png",
  },
  {
    title: "对接到第三方系统",
    image: "/images/studio/对接到第三方系统.png",
  },
];

const s2: SlideItem[] = [
  {
    title: "RTX实时光线追踪",
    subTitle: "利用RTX硬件的加速性能，在短时间内输出<br/>高质量的图片和视频。",
    image: "/images/studio/RTX实时光线追踪.png",
  },
  {
    title: "可编辑的材质",
    subTitle:
      "为时尚设计精选材质库，可自由编辑材料参数和贴图，支持<br/>导出和保存自定义库，让设计拥有无限变化。",
    image: "/images/studio/可编辑的材质.png",
  },
  {
    title: "AI配色",
    subTitle:
      "根据色彩意向图或预定颜色组，自动生成配色，实时判断多种颜色<br/>组合的可能性，激发创意灵感，节省重复枯燥的操作时间。",
    image: "/images/studio/AI配色.png",
  },
  {
    title: "照片级渲染出图",
    subTitle:
      "最高4K质量和720度全景展示，满足你对精度的极致要求。云<br/>端渲染，智能队列管理，让本地设备资源释放，不妨碍其他工作。",
    image: "/images/studio/照片级渲染出图.png",
  },
  {
    title: "灯光环境系统",
    subTitle:
      "高动态范围图像全景环境图外，支持自定义添加<br/>HDR资源，改进性的采样，精准还原光照效果。",
    image: "/images/studio/灯光环境系统.png",
  },
  {
    title: "3D分解图",
    subTitle: "使用3D可视化分解产品，让结构评审更直观。",
    image: "/images/studio/3D分解图.png",
  },
  {
    title: "3D素材库",
    subTitle: "Versebook、款式模型库、咬花库、HDR环境素材库。",
    image: "/images/studio/3D素材库.png",
  },
];
const s3: SlideItem[] = [
  {
    title: "尖端的速度和性能",
    subTitle: "Apple M2芯片、Surface",
    image: "/images/studio/RTX实时光线追踪.png",
  },
  {
    title: "专业的合作伙伴",
    subTitle: "Pantone、Coloro、NIVIDIA",
    image: "/images/studio/可编辑的材质.png",
  },
  {
    title: "插件生态",
    subTitle: "Adobe、CLO",
    image: "/images/studio/AI配色.png",
  },
  {
    title: "数据生态",
    subTitle: "GITF/USD转换",
    image: "/images/studio/数据生态.png",
  },
];
const Studio: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>时谛智能</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.studio}>
        <TopBanner />
        <TextBanner
          items={[
            {
              title: "即时",
              subTitle: "所见即所得",
              description:
                "您的数字设计助手，可随时随地与团队进行可视化、清晰快速的沟通。",
            },
            {
              title: "协同",
              subTitle: "协作式设计审查",
              description:
                "汇总各地团队的设计变更、评论和标注意见，轻松查看项目信息，实现高效决策。",
            },
            {
              title: "可追溯",
              subTitle: "版本存储管理",
              description: "便于刷新和恢复任何范围的颜色和材料组合。",
            },
          ]}
        />
        <div className="container py-20">
          <div className="grid grid-cols-3 gap-25">
            <Card icon="/images/studio/messages.png" title="协同" />
            <Card icon="/images/studio/cpu-charge.png" title="渲染" />
            <Card icon="/images/studio/tree.png" title="生态合作" />
          </div>
          <div className={styles.power}>POWERFUL</div>
        </div>

        <div className="container py-20">
          <div className="flex">
            <div className={styles["card-wrap"]}>
              <Card icon="/images/studio/messages.png" title="协同" />
            </div>
            <div className={styles["slider-wrap"]}>
              <Slider items={s1} />
            </div>
          </div>
        </div>

        <div className="container py-20">
          <div className="flex">
            <div className={styles["card-wrap"]}>
              <Card icon="/images/studio/tree.png" title="渲染" />
            </div>
            <div className={styles["slider-wrap"]}>
              <Slider items={s2} />
            </div>
          </div>
        </div>

        <div className="container py-20">
          <div className="flex">
            <div className={styles["card-wrap"]}>
              <Card icon="/images/studio/cpu-charge.png" title="生态合作" />
            </div>
            <div className={styles["slider-wrap"]}>
              <Slider items={s3} />
            </div>
          </div>
        </div>

        <Number />

        <TabView />

        <Download />

        <div className={styles.relation}>
          <h2>如何使用RevoFIM加速商品开发？</h2>
          <Relation />
        </div>
        <div className="bg-black">
          <div className="container py-32">
            <h2 className="section-title">联系我们</h2>
            <h3 className="section-subtitle">
              释放设计灵感，即刻开启时尚数字新体验
            </h3>
            <ContactForm page="studio" />
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Studio;
