//const client = new PocketBase("https://pocketbase.io");

import e2e from "assets/images/home/way.png";
import Brand from "components/Brand";
import Button from "components/Button";
import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import Progress from "components/Progress";
import SectionCard from "components/SectionCard";
import Step from "components/Step";
import Tabbar from "components/Tabbar";
import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "styles/Home.module.scss";

import Banner from "../components/Banner";
import Case from "../components/Case";
import Category from "../components/Category";
const Home: NextPage = () => {
  const [tabActiveIndex, setTabActiveIndex] = useState<number>(0);
  const [bannerIndex, setBannerIndex] = useState<number>(0);
  const [progress, setProgress] = useState<number>(0);
  useEffect(() => {
    //client.records.getList("posts", 1, 20, {});
  }, []);

  return (
    <Layout>
      <Head>
        <title>时谛智能</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </Layout>
  );
};

export default Home;
