import cn from "classnames";
import BigCard from "components/BigCard";
import CommonBanner from "components/CommonBanner";
import ContactForm from "components/ContactForm";
import Layout from "components/Layout";
import SectionCard from "components/SectionCard";
import SmallCard from "components/SmallCard";
import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import styles from "styles/Verse.module.scss";

const Versekit: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Versekit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CommonBanner
          id="manager-banner"
          image="/images/manager.jpg"
          title={
            <div className="relative w-150">
              <Image
                src="/images/library/library-title.png"
                className="image"
                fill
                alt=""
              />
            </div>
          }
          description="数字资产存储中枢，多场景赋能产品创意设计，让管资产、玩设计、做产品的方法变得更简单、高效。"
          buttonText="免费使用"
        />
        {/** 产品亮点 */}
        <div className="bg-rev-bg-black-0B relative">
          <div className={styles["blur-bg"]}></div>
          <div className="container">
            <h2 className="section-title">产品亮点</h2>
            <div className={cn(styles.highlight, "container pt-15")}>
              <BigCard
                icon="/images/trends/h1.png"
                title="电商数据分析"
                description="与阿里官方深度合作，覆盖淘宝/天猫40万+店铺的sku销售数据，提供多维度的分析能力"
              />
              <BigCard
                icon=""
                title="电商数据分析"
                description="与阿里官方深度合作，覆盖淘宝/天猫40万+店铺的sku销售数据，提供多维度的分析能力"
              />
              <BigCard
                icon=""
                title="电商数据分析"
                description="与阿里官方深度合作，覆盖淘宝/天猫40万+店铺的sku销售数据，提供多维度的分析能力"
              />
              <BigCard
                icon=""
                title="电商数据分析"
                description="与阿里官方深度合作，覆盖淘宝/天猫40万+店铺的sku销售数据，提供多维度的分析能力"
              />
            </div>
            <SectionCard
              title={"时谛智能 X 天猫TMIC 为商家带来的价值解析"}
              subtitle=" 是立足于阿里巴巴全渠道的数字化新品研发平台。TMIC结合大数据分析和小样本调研，助力品牌定位目标人群，洞察市场机会，研发创新产品，以及优化营销策略。"
              mode={"left"}
              className={"py-40"}
              list={[
                {
                  icon: "/images/library/标签化数据-1.png",
                  text: "更快捷：速度提升",
                },
                {
                  icon: "/images/library/标签化数据-2.png",
                  text: "更高效：款式数量",
                },
                {
                  icon: "/images/library/标签化数据-3.png",
                  text: "更精准：趋势分析",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/标签化数据.png"
                  fill
                  className="image"
                  alt="标签化数据"
                />
              </div>
            </SectionCard>
          </div>
        </div>
        <div className="bg-rev-bg-contact relative">
          <div className={styles["lib-bg"]}></div>

          <div className="container">
            <div className="my-10">
              <h2 className="section-title" style={{ marginTop: 0 }}>
                三大功能场景&解决方案
              </h2>
            </div>
            <div className="grid grid-cols-3 gap-7">
              <SmallCard
                icon="/images/trends/灵感捕捉.png"
                title="灵感捕捉"
                description="聚合全网潮搭的海量鞋服款式库"
              />
              <SmallCard
                icon="/images/trends/市场洞察.png"
                title="市场洞察"
                description="聚合全网潮搭的海量鞋服款式库"
              />
              <SmallCard
                icon="/images/trends/AI智能创款.png"
                title="AI智能创款"
                description="聚合全网潮搭的海量鞋服款式库"
              />
            </div>
            <div className="h-16"></div>

            <SectionCard
              grid
              title={"市场分析，透视历史"}
              subtitle="基于全网电商市场海量的历史销售数据进行探索，全方位多角度不断深入细分，为企划与设计提供有力的数据支持"
              mode={"right"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/智能化搜索-1.png",
                  text: "全方位的市场动向分析",
                  description: "横向分析行业大盘、竞争对手的布局，掌握市场动向",
                },
                {
                  icon: "/images/library/智能化搜索-2.png",
                  text: "多层级的品类透视分析",
                  description:
                    "纵向分析品类、价格带、品牌、店铺、款式再到颜色、材料等粒度，定位到具体的设计元素",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/智能化搜索.png"
                  fill
                  className="image"
                  alt="智能化搜索"
                />
              </div>
            </SectionCard>
            <SectionCard
              title={"可视化管理"}
              subtitle="利用AI算法的能力，针对当前市场上最热门的店铺、款式等进行属性的分解与分析，寻找出当下市场上最热销、最受欢迎的款式、颜色、风格、面料等"
              mode={"left"}
              className={styles["card-section"]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/可视化管理.png"
                  fill
                  className="image"
                  alt="可视化管理"
                />
              </div>
            </SectionCard>
            <SectionCard
              grid
              title={"整合数字资产"}
              subtitle="打通外部软件及工具，整合并沉淀数字资产"
              mode={"right"}
              className={styles["card-section"]}
              list={[
                {
                  icon: "/images/library/智能化搜索-1.png",
                  text: "全方位的市场动向分析",
                  description: "横向分析行业大盘、竞争对手的布局，掌握市场动向",
                },
                {
                  icon: "/images/library/智能化搜索-2.png",
                  text: "多层级的品类透视分析",
                  description:
                    "纵向分析品类、价格带、品牌、店铺、款式再到颜色、材料等粒度，定位到具体的设计元素",
                },
                {
                  icon: "/images/library/智能化搜索-1.png",
                  text: "全方位的市场动向分析",
                  description: "横向分析行业大盘、竞争对手的布局，掌握市场动向",
                },
                {
                  icon: "/images/library/智能化搜索-2.png",
                  text: "多层级的品类透视分析",
                  description:
                    "纵向分析品类、价格带、品牌、店铺、款式再到颜色、材料等粒度，定位到具体的设计元素",
                },
                {
                  icon: "/images/library/智能化搜索-2.png",
                  text: "多层级的品类透视分析",
                  description:
                    "纵向分析品类、价格带、品牌、店铺、款式再到颜色、材料等粒度，定位到具体的设计元素",
                },
              ]}
            >
              <div className={cn(styles["image-wrap"], " w-4/5")}>
                <Image
                  src="/images/library/整合数字资产.png"
                  fill
                  className="image"
                  alt="整合数字资产"
                />
              </div>
            </SectionCard>
          </div>
        </div>
        <div className="bg-rev-bg-black-0B">
          <div className="container pb-32">
            <h2 className="section-title">联系我们</h2>
            <h3 className="section-subtitle">开启资产数字化之路</h3>
            <ContactForm page="home" />
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default Versekit;
